<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
    <Folder Include="Templates\Camera\ThirdPerson\scripts\" />
    <Folder Include="Templates\Gameplay\HSM\scripts\" />
    <Folder Include="Templates\Audio\" />
    <Folder Include="Templates\Networking\Fishnet-P2P\scripts\" />
    <Folder Include="Templates\Steam\SteamOverlay\scripts\" />
    <Folder Include="Templates\UI\" />
    <Folder Include="Templates\SaveSystem\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.2" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BootStrapper.Core\BootStrapper.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Projects\ProjectList.axaml.cs">
      <DependentUpon>ProjectList.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Projects\ProjectCreate.axaml.cs">
      <DependentUpon>ProjectCreate.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Templates\TemplateCreate.axaml.cs">
      <DependentUpon>TemplateCreate.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Templates\TemplateInfoView.axaml.cs">
      <DependentUpon>TemplateInfoView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\HomeView.axaml.cs">
      <DependentUpon>HomeView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
