<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaXaml Remove="Templates\**" />
    <Compile Remove="Templates\**" />
    <EmbeddedResource Remove="Templates\**" />
    <None Remove="Templates\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.0.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.0.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.0.2" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.1" />
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BootStrapper.Core\BootStrapper.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Projects\ProjectListView.axaml.cs">
      <DependentUpon>ProjectListView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Projects\ProjectCreateView.axaml.cs">
      <DependentUpon>ProjectCreateView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Projects\ProjectInfoView.axaml.cs">
      <DependentUpon>ProjectInfoView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Templates\TemplateCreateView.axaml.cs">
      <DependentUpon>TemplateCreateView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Templates\TemplateInfoView.axaml.cs">
      <DependentUpon>TemplateInfoView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\HomeView.axaml.cs">
      <DependentUpon>HomeView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SidebarView.axaml.cs">
      <DependentUpon>SidebarView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Templates\TemplateListView.axaml.cs">
      <DependentUpon>TemplateListView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\CreditsView.axaml.cs">
      <DependentUpon>CreditsView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\SettingsView.axaml.cs">
      <DependentUpon>SettingsView.axaml</DependentUpon>
    </Compile>
    <Compile Update="Views\Templates\OfficialTemplateSView.axaml.cs">
      <DependentUpon>OfficialTemplatesView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>
